<?php
/**
 * @file
 * Definición de variables globales
 */
$root = $_SERVER['DOCUMENT_ROOT'];

//camino de decs-ld
define("PATH_DECS_LD", $root."/apps-ld/decs-ld/");

//camino de lilacs-ld
define("PATH_LILACS_LD", $root."/apps-ld/lilacs-ld/");

//camino de common
define("PATH_COMMON_LD", $root."/apps-ld/common/");

//url para encuestar las entidades de la aplicacion
define("URL_LILACS_LD", "http://lilacs.sld.cu/entity/");
?>
